#!/usr/bin/env bash
# Thanks to Zato, rafal-k

cd /opt/zato
sleep 1
#sudo -u postgres \
#    /usr/lib/postgresql/10/bin/postgres \
#    -D /var/lib/postgresql/10/main \
#    -c config_file=/etc/postgresql/10/main/postgresql.conf
source /opt/zato/env/build-zato-image.sh start-zato-odb-cluster
