#!/usr/bin/env bash
# Thanks to Zato, rafal-k

cd /opt/zato

# To give servers ample time to start
sleep 30

rm -f /opt/zato/env/scheduler/run/pidfile
/opt/zato/current/bin/zato start /opt/zato/env/scheduler/run --fg
