#!/usr/bin/env bash
# Thanks to Zato, rafal-k

cd /opt/zato

rm -f /opt/zato/env/load_balancer/run/zato-lb-agent.pid
rm -f /opt/zato/env/load_balancer/run/pidfile
/opt/zato/current/bin/zato start /opt/zato/env/load_balancer/run --fg
