apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./migration-tools parse --docker-file docker-compose-no-net.yml
    kompose.version: 1.16.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: scheduler
  name: scheduler
spec:
  replicas: 0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: scheduler
    spec:
      containers:
      - image: scheduler
        name: scheduler
        resources: {}
      restartPolicy: Always
status: {}
