apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./migration-tools parse --docker-file docker-compose-no-net.yml
    kompose.version: 1.16.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web-admin
  name: web-admin
spec:
  replicas: 0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web-admin
    spec:
      containers:
      - image: web-admin
        name: web-admin
        ports:
        - containerPort: 8183
        resources: {}
      restartPolicy: Always
status: {}
