#!/usr/bin/env bash
# Thanks to Zato, rafal-k

cd /opt/zato

# To give servers ample time to start
sleep 30

#source /opt/zato/env/build-zato-image.sh build-zato-server
rm -f /opt/zato/env/server01/run/pidfile
/opt/zato/current/bin/zato start /opt/zato/env/server01/run --fg
